# Generated by Django 5.2.1 on 2025-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashbin',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trashbin',
            name='mahalla',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trashbin',
            name='status',
            field=models.CharField(choices=[('FILLED', 'To‘ldi'), ('EMPTY', 'Bo‘sh')], max_length=20),
        ),
    ]
